spring:
  application:
    name: thesis-manager
  datasource:
    url:
    username:
    password:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

app:
  storage:
    root: